# Generated by Django 4.1.7 on 2023-11-05 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
            ],
            options={
                'verbose_name_plural': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.categorie', verbose_name='Catégorie')),
                ('situa_geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.localisation', verbose_name='Localisation')),
            ],
            options={
                'verbose_name_plural': 'Etablissement',
            },
        ),
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.categorie', verbose_name='Catégorie')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.etablissement', verbose_name='Etablissement')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
    ]
