# Generated by Django 4.1.7 on 2023-11-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestotelMap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='situa_geo',
        ),
        migrations.DeleteModel(
            name='Appartenir',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
        migrations.DeleteModel(
            name='Localisation',
        ),
    ]
