# Generated by Django 4.1.7 on 2023-11-12 14:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestotelMap', '0002_remove_etablissement_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
            ],
            options={
                'verbose_name_plural': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Etab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('catego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.catego', verbose_name='Catégorie')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.local', verbose_name='Localisation')),
            ],
            options={
                'verbose_name_plural': 'Etablissement',
            },
        ),
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.catego', verbose_name='Catégorie')),
                ('etab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.etab', verbose_name='Etablissement')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
    ]
